LunarLander-v3:
  policy: MlpPolicy
  n_timesteps: 500000
  learning_rate: 0.001
  buffer_size: 200000
  learning_starts: 10000
  batch_size: 256
  train_freq: 4
  gradient_steps: 1
  target_update_interval: 1000
  exploration_fraction: 0.2
  exploration_final_eps: 0.05
  policy_kwargs: dict(net_arch=[256, 256])
  n_envs: 1
