LunarLander-v3:
  policy: MlpPolicy
  n_timesteps: 500000
  learning_rate: 0.0003
  n_envs: 8
  n_steps: 1024
  batch_size: 1024
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  policy_kwargs: dict(net_arch=[256, 256])
SectorCREnv-v0:
  policy: MlpPolicy
  n_timesteps: 100000
  learning_rate: 0.0003
  n_envs: 1
  n_steps: 2048
  batch_size: 256
  n_epochs: 10
  gamma: 0.995
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  policy_kwargs: dict(net_arch=[256, 256])
  env_wrapper: gymnasium.wrappers.FlattenObservation
