SectorCREnv-v0:
  policy: MlpPolicy
  n_timesteps: 100000
  learning_rate: 0.0003
  buffer_size: 100000
  learning_starts: 10000
  batch_size: 256
  train_freq: 1
  gradient_steps: 1
  tau: 0.005
  gamma: 0.99
  ent_coef: auto
  policy_kwargs: dict(net_arch=[256, 256])
  env_wrapper: gymnasium.wrappers.FlattenObservation
